disabled_rules:
  - strict_fileprivate
  - switch_case_alignment
  - vertical_parameter_alignment_on_call
excluded:
  - .build
parent_config: https://github.com/TextsHQ/swiftlint-config/raw/main/base.yml
